package com.meksconway.areyouexpert.util

const val GENERAL_KNOWLEDGE = "cat_general_knowledge"
const val BOOKS = "cat_books"
const val FILM = "cat_film"
const val MUSIC = "cat_music"
const val MUSICALS_THEATRES = "cat_musicals_and_theatres"
const val TELEVISION = "cat_television"
const val VIDEO_GAMES = "cat_video_games"
const val BOARD_GAMES = "cat_board_games"
const val SCIENCE_NATURE = "cat_science_and_nature"
const val COMPUTERS = "cat_computers"
const val MATHEMATICS = "cat_mathematics"
const val MYTHOLOGY = "cat_mythology"
const val SPORTS = "cat_sports"
const val GEOGRAPHY = "cat_geography"
const val HISTORY = "cat_history"
const val POLITICS = "cat_polıtıcs"
const val ART = "cat_art"
const val CELEBRITIES = "cat_celebrities"
const val ANIMALS = "cat_animals"
const val VEHICLES = "cat_vehicles"
const val COMICS = "cat_comics"
const val GADGETS = "cat_gadget"
const val JAPANESE_ANIME_MANGA = "cat_japanese_anime_and_manga"
const val CARTOON_ANIMATION = "cat_cartoon_and_animations"